@origin = http://localhost:4000
@host = {{origin}}/api

###
# @name createUser

POST {{host}}/create-test-user

###
# @name login
POST {{host}}/auth/sign-in/email
Content-Type: application/json
Origin: {{origin}}

{
	"email": "{{createUser.response.body.user.user.email}}",
	"password": "{{createUser.response.body.password}}"
}

###
# @name sessionTest

GET {{host}}/auth/get-session
Cookie: {{login.response.headers.set-cookie}}

###
# @name logout

POST {{host}}/auth/sign-out
Cookie: {{login.response.headers.set-cookie}}
Content-Type: application/json
Origin: {{origin}}

{}

###
# @name deleteTestUsers

POST {{host}}/delete-test-users

